<a href="https://colab.research.google.com/github/accessrj/Jm-Khandual/blob/main/Python_Basics_Sep4_Jk.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import math


In [2]:
math.sqrt(256)

16.0

In [3]:
3>10

False

In [4]:
7<25

True

In [5]:
10==10

True

In [6]:
20+10

30

In [7]:
100-39

61

In [8]:
585*3738

2186730

In [9]:
37238/27

1379.1851851851852

In [10]:
10==39

False

In [11]:
10<>10

SyntaxError: ignored

In [12]:
10!=10

False

In [13]:
10<>20

SyntaxError: ignored

In [14]:
5<=10

True

In [15]:
5>=9


False

In [16]:
7&10

2

In [17]:
3&5&u

NameError: ignored

In [18]:
3&5&10

0

In [19]:
12|13

13

In [20]:
12|11

15

In [21]:
(10>20)&(20>10)

False

In [22]:
(10>20)|(10<16)

True

In [23]:
a=10>20

In [24]:
a=10>20
print(a)

False


In [25]:
b=20>10
print(b)

True


In [26]:
a|b

True

In [27]:
a&b

False

In [29]:
i=0
whilei<=5
print(i)
i=i+1

NameError: ignored

In [30]:
i=0
while i<=5:
  print(i)
  i=i+1

0
1
2
3
4
5


In [31]:
i=0
while i<=5:
  print(i)
  i=i+1
  


0
1
2
3
4
5


In [33]:
i=0
while i<=5:
  print(i)
  i=i+1
  

0
1
2
3
4
5


In [34]:
i=0
while i<=5:
  print(i)
  i=i+1
print("loop ends")


0
1
2
3
4
5
loop ends


In [37]:
i=10
while i<=10:
print(i)
i=i+1



IndentationError: ignored

In [38]:
range(6)

range(0, 6)

In [39]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [40]:
for i in range(6):
  print("hello")

hello
hello
hello
hello
hello
hello


In [41]:
for i in range(5)

SyntaxError: ignored

In [42]:
for i in range(5):
  print ("hello")

hello
hello
hello
hello
hello


In [43]:
import numpy as np
from numpy.random import randn

In [45]:
result = None
x=randn()
if x>1:
  result="greater than 1"
print(x)
print(result)

-1.8131519546693708
None


In [51]:
result = None
x=randn()
if x>1:
  result="greater than 1"
else:
  result="less than 1"
print(x)
print(result)

3.3237831940159004
greater than 1


In [61]:
## chained if statement 
result = None
x=randn()
if x>1:
  result="greater than 1"
elif x<=-1:
  result="less than -1"
else:
  result="between -1 and 1"
print(x)
print(result)

-1.9625200156834146
less than -1


In [62]:
## CREATING A LIST

type(list1)list1 = [1,2,4,10,'abc',"good job", true , 29.33]


NameError: ignored

In [63]:
list1 = [1,2,4,10,'abc',"good job", True , 29.33]
type(list1)


list

In [64]:
type(list1)

list

In [65]:
list1[-1]

29.33

In [66]:
list1[4]

'abc'

In [70]:
list1[2]='jk'
list1

[1, 2, 'jk', 10, 'abc', 'good job', True, 29.33]

In [71]:

list1[2:6]

['jk', 10, 'abc', 'good job']

In [72]:
list1[::2]

[1, 'jk', 'abc', True]

In [73]:
list1[::-1]

[29.33, True, 'good job', 'abc', 10, 'jk', 2, 1]

In [74]:
tuple1= (10,'abc', 35.93)
tuple1[1]

'abc'

In [75]:
range(10)

range(0, 10)

In [76]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [77]:
print("list")

list


In [78]:
x=(5,366,4,2,7,9)

In [79]:
len(x)

6

In [80]:
x=aghf
type(x)

NameError: ignored

In [ ]:
from abc import abs

In [ ]:
range(7
    )

In [81]:
#arrays
import numpy as np
a= np.array(list1)
print(a)

['1' '2' 'jk' '10' 'abc' 'good job' 'True' '29.33']


In [82]:
a

array(['1', '2', 'jk', '10', 'abc', 'good job', 'True', '29.33'],
      dtype='<U32')

In [83]:
b =  np.array([2345, 6789, 9876,1456, -1234])
b.mean()

3846.4

In [84]:
b

array([ 2345,  6789,  9876,  1456, -1234])

In [85]:
b[::2]

array([ 2345,  9876, -1234])

In [86]:
b[1::2]

array([6789, 1456])

In [87]:
c= b[2:4]

In [88]:
c

array([9876, 1456])

In [89]:
c[:] = 222

In [90]:
c

array([222, 222])

In [91]:
b

array([ 2345,  6789,   222,   222, -1234])